### ISSUE TITLE
Why to push the Rails logs to the STDOUT?

### ISSUE THREAD

**Issue by fguillen** [michal-kazmierczak/opentelemetry-rails-example#2]
`promtail` is perfectly capable of scraping the logs from `my-app/logs/` and is simpler and more intuitive:

```
  promtail:
    image: grafana/promtail:3.0.0
    volumes:
      - ./docker/promtail/config.yml:/etc/promtail/config.yml
      - ./log/:/var/log/rails/:ro
    command: -config.file=/etc/promtail/config.yml
```

I am asking because your repo inspires me, and it helped me a lot. I want to know I am not missing anything.

Thanks for your work
